# Generated by Django 6.0.2 on 2026-03-02 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Kutubxonachi',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='admin',
            new_name='kutubxonachi',
        ),
        migrations.AlterField(
            model_name='kitob',
            name='muallif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.muallif'),
        ),
        migrations.AlterField(
            model_name='kitob',
            name='sahifa',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='kitob_soni',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='kurs',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
